---
name: Linters and formatters

on:                           # yamllint disable-line rule:truthy
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Terraform linter
        run: |
          terraform version
          terraform fmt -check -recursive

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install yamllint
        run: pip install yamllint

      - name: YAML linter
        run: |
          yamllint --strict .

      - name: YAML linter
        run: |
          podman run --rm -i ghcr.io/hadolint/hadolint < src/grafana/Dockerfile
          podman run --rm -i ghcr.io/hadolint/hadolint < src/postgres/Dockerfile
